---
deployment:
  tasks:
    - /bin/echo "Installing admin portal production dependencies"
    - source /opt/cpanel/ea-nodejs22/bin/nodevenv /home/hlyjphxp/nodeapps/rfcity-admin 22 && cd /home/hlyjphxp/nodeapps/rfcity-admin/admin-portal && npm ci --omit=dev
    - /bin/echo "Building Next.js admin portal"
    - source /opt/cpanel/ea-nodejs22/bin/nodevenv /home/hlyjphxp/nodeapps/rfcity-admin 22 && cd /home/hlyjphxp/nodeapps/rfcity-admin/admin-portal && npm run build
    - /bin/echo "Touching Passenger restart file"
    - cd /home/hlyjphxp/nodeapps/rfcity-admin/admin-portal && mkdir -p tmp && touch tmp/restart.txt

