---
deployment:
  tasks:
    - /bin/echo "Installing admin portal runtime dependencies only"
    - cd /home/hlyjphxp/nodeapps/rfcity-admin/admin-portal && /home/hlyjphxp/nodevenv/nodeapps/rfcity-admin/22/bin/npm ci --omit=dev
    - /bin/echo "Restarting Passenger"
    - cd /home/hlyjphxp/nodeapps/rfcity-admin/admin-portal && mkdir -p tmp && touch tmp/restart.txt

